m = int(input("donner le N° du mois : "))

if m == 1 : print("Janvier")
elif m == 2 : print("Février")
elif m == 3 : print("Mars")
elif m == 4 : print("Avril")
elif m == 5 : print("Mai")
elif m == 6 : print("Juin")
elif m == 7 : print("Juillet")
elif m == 8 : print("Août")
elif m == 9 : print("Septembre")
elif m==10 : print("Octobre")
elif m== 11 : print("Novembre")
elif m== 12 : print("Décembre")
else : print("Mois invalide")

match m :
    case 1: print("Janvier")
    case 2: print("Février")
    case 3: print("Mars")
    case 4: print("Avril")
    case 5 : print("Mai")
    case 6 : print("Juin")
    case 7 : print("Juillet")
    case 8 : print("Août")
    case 9 : print("Septembre")
    case 10 : print("Octobre")
    case 11 : print("Novembre")
    case 12 : print("Décembre")
    case _ : print("Mois invalide")